### ISSUE TITLE
Get-WinADForestDetails should support Credential

### ISSUE THREAD

**Issue by adriandeller** [EvotecIT/PSSharedGoods#42]
the function `Get-WinADForestDetails` is called first in the `ADEssentials` function `Test-LDAP`
while I can provide specific credentials to `Test-LDAP`, they are not (cannot) handed over to  `Get-WinADForestDetails` to discover domains and domain controllers in the forest.
this change would be rerquired to be able to make a call like:
`Test-LDAP -Forest forest.domain.com -Credential (Get-Credential -UserName FOREST\username)`
This leads currently to an error:
`WARNING: Get-WinADForestDetails - Error discovering DC for Forest - Authentication failed, see inner exception.`

**Comment by PrzemyslawKlys** [comment]
Should be fixed by (and include fixes for other credentials)
- https://github.com/EvotecIT/PSSharedGoods/pull/43

**Comment by adriandeller** [comment]
Thank you for addressing this issue so quickly!
But now I'm a little bit confused ... 
Why is there also a function with the name `Get-WinADForestDetails` in the `ADEssentials` module file `\ADEssentials\0.0.267\ADEssentials.psm1`?
On a machine where I only install `ADEssentials` the issue is still there of course.
What am I missing here?

**Comment by PrzemyslawKlys** [comment]
PSPublishModule that builds the modules has this feature which detects which functions are in use and is able to merge functions from different modules into final module (adessentials, gpozaurr etc) to not bring full dependency of 200-300functions with PSSharedGoods. 

This means development version locally uses PSSharedGoods so unified, direct approach, but during build/publish mode it's able to get rid of PSWriteColor,PSSharedGoods and build dependency free module. Of course there are limits to this integration and it only works if there are no dll dependencies, or other files.. like PSWriteHTML is not gonna easily integrate the same way. But a lot of modules can "borrow" functions and not have any dependencies in PSGallery.

**Comment by PrzemyslawKlys** [comment]
In other words - I need to publish new version of ADEssentials, GPOZaurr etc to fix this issue.
